# Generated by Django 4.2.8 on 2023-12-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyweb', '0003_skill_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_image',
            field=models.ImageField(blank=True, null=True, upload_to='department_images/'),
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
